version: "2"
services:
  app:
    env_file:
      - ./config/docker/app.env
    working_dir: /var/www
    volumes:
      - ./:/var/www
    build:
      context: ./config/docker/
      dockerfile: app.dockerfile
    links:
      - cache
      - database
    expose:
      - "9000"

  composer:
    restart: 'no'
    image: composer/composer
    volumes:
      - ./:/app
    command: install
  web:
    build:
      context: ./
      dockerfile: config/docker/web.dockerfile
    volumes_from:
      - app
    links:
      - app
    expose:
      - "80"
    ports:
      - "8080:80"

  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    expose:
      - "3306"



  cache:
    image: redis:3.0-alpine
    expose:
      - "6379"

volumes:
  dbdata:
